### ISSUE TITLE
make crop-cam thows a 'std::exception'

### ISSUE THREAD

**Issue by Ricky-rick** [hamidzr/webcam-mods#18]
Hope you can help.
I have followed the instruction video but when i run the `make crop-cam` command i am getting the following error:
```
pipenv run python entry.py crop-cam
starting with config {'crop_dims': [640, 480], 'crop_pos': [0, 0], 'pad_size': [0, 0]}
config file not found at .webcam.conf
begin passing from #Webcam to #VirtualCam
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Traceback (most recent call last):
  File "entry.py", line 133, in <module>
    app()
  File "/home/rick/.local/share/virtualenvs/webcam-mods-wTpII5o_/lib/python3.8/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/rick/.local/share/virtualenvs/webcam-mods-wTpII5o_/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/rick/.local/share/virtualenvs/webcam-mods-wTpII5o_/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/rick/.local/share/virtualenvs/webcam-mods-wTpII5o_/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/rick/.local/share/virtualenvs/webcam-mods-wTpII5o_/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/rick/.local/share/virtualenvs/webcam-mods-wTpII5o_/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/rick/.local/share/virtualenvs/webcam-mods-wTpII5o_/lib/python3.8/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "entry.py", line 48, in crop_cam
    live_loop(base_mod)
  File "/home/rick/Desktop/tmp/webcam-mods/src/loopback.py", line 34, in live_loop
    with fOut as (cam, outp_props):
  File "/home/rick/Desktop/tmp/webcam-mods/src/input/input.py", line 73, in __enter__
    return super().__enter__() # type: ignore
  File "/home/rick/Desktop/tmp/webcam-mods/src/input/input.py", line 24, in __enter__
    return (self, self.setup())
  File "/home/rick/Desktop/tmp/webcam-mods/src/output/pyvirtcam.py", line 28, in setup
    self.cam = pyvirtualcam.Camera(width=self.width, height=self.height,
  File "/home/rick/.local/share/virtualenvs/webcam-mods-wTpII5o_/lib/python3.8/site-packages/pyvirtualcam/camera.py", line 219, in __init__
    raise RuntimeError('\n'.join(errors))
RuntimeError: 'v4l2loopback' backend: std::exception
make: *** [Makefile:7: crop-cam] Error 1
```

The decribe devices outputs
```
v4l2-ctl --list-device
v4l-cam (platform:v4l2loopback-000):
	/dev/video10

Integrated_Webcam_HD: Integrate (usb-0000:00:14.0-12):
	/dev/video0
	/dev/video1

v4l2-ctl --list-formats-ext
ioctl: VIDIOC_ENUM_FMT
	Type: Video Capture

	[0]: 'MJPG' (Motion-JPEG, compressed)
		Size: Discrete 1280x720
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 960x540
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 848x480
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 640x480
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 640x360
			Interval: Discrete 0.033s (30.000 fps)
	[1]: 'YUYV' (YUYV 4:2:2)
		Size: Discrete 640x480
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 640x360
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 424x240
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 320x240
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 320x180
			Interval: Discrete 0.033s (30.000 fps)
		Size: Discrete 160x120
			Interval: Discrete 0.033s (30.000 fps)

```

**Comment by hamidzr** [comment]
not sure if it's related but the video is quite old at this point. I am planning to update

**Comment by miguelhdezsob** [comment]
I had the same error on Ubuntu 20.4, even after making sure to run `make add-video-dev`.
I am pretty sure that this error is caused by `v4l2loopback` in Ubuntu.
I ended up trying out a different project, and after compiling and installing `v4l2loopback` from source, I was able to run that project as expected:
https://github.com/fangfufu/Linux-Fake-Background-Webcam#ubuntu-1804


So perhaps a similar workaround might be needed for this project, I haven't checked if it would work.

**Comment by hamidzr** [comment]
thanks, I'll take a look. would having reinstalled v4l2loopback for that project help anything here? I test on Arch Linux I'll see if anything would be different on Ubuntu.

**Comment by miguelhdezsob** [comment]
> thanks, I'll take a look. would having reinstalled v4l2loopback for that project help anything here? I test on Arch Linux I'll see if anything would be different on Ubuntu.

I just quickly tested this project again after reinstalling `v4l2loopback` and unfortunately I still get the same error. So further investigation in Ubuntu might be needed

**Comment by hamidzr** [comment]
FYI since it might affect this issue: I switched the package the way the v4l2loopback device is used to address the issue mentioned [here](https://github.com/hamidzr/webcam-mods/issues/16#issuecomment-991987082) and make debugging easier. You'd probably need to use pipenv to install as one of the dependencies is being installed from a git url.
